environment: staging
server:
  address: "127.0.0.1:8083"
parsimap:
  token: "p1da5eaa82ea55494598f43f1fa1e0f3fc3fb63849"
sentry:
  DSN: https://6236975c5fe246179d4dd2094cc9b287@sentry.eways.dev/4
otp:
  engine: constant
  exp_sec: 30
  config:
    code: "123456"
sms:
  provider: "stdout"
  sender: "sender"
  org: "org"
phone_verifier:
  provider: "dumb"
  config:
    response: true
    url: "test"
rate_limiter:
  max_customer_regreqs: 49999
  customer_regreq_reset_interval_hrs: 1
http:
  port: 8083
db:
  host: 127.0.0.1
  port: 5432
  user: "postgres"
  password: "postgres"
  name: "gogogo"
  driver: "postgres"
  ssl_mode: "disable"